# Generated by Django 4.2.6 on 2023-11-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_articlecomment_parent_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('title_text', models.TextField()),
                ('content_text', models.TextField()),
                ('category_text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='article_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='api.article'),
        ),
    ]
