# Generated by Django 4.2.6 on 2023-12-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_siteuser_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='category',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='category',
            field=models.ManyToManyField(related_name='user', to='api.category'),
        ),
    ]
